date: "0404"
resume: 0
test: 0
localize: 0 
debug: 0 
epochs: 5
# lr: 4e-3 #0.0001 (1e-4)
lr: 1e-4 #0.0001 (1e-4)
stereo: 0 
sequence: 1 


direction: "S2GP"
rotation_range: 10.
shift_range_lat: 20.
shift_range_lon: 20.
level: -1  # VGGUnet output 3 levels: 0, 1, 2
N_iters: 5
Load: 0

coe_shift_lat: 100.
coe_shift_lon: 100.
coe_heading: 100. 
coe_L1: 100.
coe_L2: 100.
coe_L3: 100.
coe_L4: 100.
metric_distance: 5.
loss_method: 0
using_weight: 0
damping: 0.1
train_damping: 0

    # parameters below are used for the first-step metric learning traning
negative_samples: 32
use_conf_metric: 0

Optimizer: "LM"

level_first: 0
proj: "geo"
use_gt_depth: 0

dropout: 0
use_hessian: 0
visualize: 0
beta1: 0.9
beta2: 0.999


use_default_model: 0
use_transformer: True

version: ${data.version}
# version: "v1.0-trainval" # or v1.0-mini (Only 10 scenes)
# For nuscenes_dataset.py
# dataset_dir: "/home/goroyeh/nuScene_dataset/media/datasets/nuscenes"
labels_dir : "/home/goroyeh/nuScene_dataset/media/datasets/cvt_labels_nuscenes"
# root_dir:  "/home/goroyeh/nuScene_dataset/"

# On /mnt/workspace/datasets/ :
dataset_dir: "/mnt/workspace/datasets/nuScene_dataset/media/datasets/nuscenes"
root_dir:  "/mnt/workspace/datasets/nuScene_dataset/" # satmap/ or samples
# labels_dir : "/home/goroyeh/nuScene_dataset/media/datasets/cvt_labels_nuscenes/" # Actually, not used!

GrdImg_H: ${data.image.h}
GrdImg_W: ${data.image.w}
zoom_level: ${data.zoom_level}

loader: ${loader}
